defmodule LiveLlama.Repo.Migrations.CascadeDeleteMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:messages, "messages_chat_id_fkey")

    alter table(:messages) do
      modify :chat_id,
             references(:chats,
               column: :id,
               name: "messages_chat_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("ALTER TABLE messages alter CONSTRAINT messages_chat_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:messages, "messages_chat_id_fkey")

    alter table(:messages) do
      modify :chat_id,
             references(:chats,
               column: :id,
               name: "messages_chat_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end